'use client';

import { useFormState, useFormStatus } from 'react-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { getComplianceSuggestions, type FormState } from './actions';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Terminal, CheckCircle, AlertCircle, Loader2 } from 'lucide-react';

const initialState: FormState = {
  message: null,
  data: null,
  error: false,
};

function SubmitButton() {
  const { pending } = useFormStatus();

  return (
    <Button type="submit" disabled={pending}>
      {pending ? (
        <>
          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          Generating...
        </>
      ) : (
        'Get Suggestions'
      )}
    </Button>
  );
}

export function IsoComplianceClient() {
  const [state, formAction] = useFormState(getComplianceSuggestions, initialState);

  return (
    <div className="grid gap-6">
      <form action={formAction}>
        <Card>
          <CardHeader>
            <CardTitle className="font-headline">Describe Your ERP Operations</CardTitle>
            <CardDescription>
              Provide a detailed description of your current Enterprise Resource Planning (ERP) operations.
              The more detail you provide, the better the AI-powered suggestions will be.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Textarea
              name="erpDescription"
              placeholder="e.g., We use a custom-built system for project tracking. Purchase orders are created manually in spreadsheets and emailed to suppliers. Employee data is managed in a separate HR software..."
              rows={8}
              required
            />
          </CardContent>
          <CardFooter className="flex justify-between">
            <p className="text-sm text-muted-foreground">
              Suggestions are generated by AI.
            </p>
            <SubmitButton />
          </CardFooter>
        </Card>
      </form>

      {state.message && (
        <Alert variant={state.error ? 'destructive' : 'default'}>
          {state.error ? <AlertCircle className="h-4 w-4" /> : <CheckCircle className="h-4 w-4" />}
          <AlertTitle>{state.error ? 'Error' : 'Status'}</AlertTitle>
          <AlertDescription>{state.message}</AlertDescription>
        </Alert>
      )}

      {state.data?.suggestions && (
        <Card>
          <CardHeader>
            <CardTitle className="font-headline">Compliance Improvement Suggestions</CardTitle>
            <CardDescription>
              Here are some actionable suggestions to better align with ISO 9001 standards.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ul className="space-y-4">
              {state.data.suggestions.map((suggestion, index) => (
                <li key={index} className="flex items-start gap-4">
                  <span className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10 text-primary">
                    <CheckCircle className="h-5 w-5" />
                  </span>
                  <p className="flex-1 pt-1">{suggestion}</p>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
